version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
      MONGO_INITDB_DATABASE: KAFKA
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: postgres:latest
    container_name: profiledb
    environment:
      POSTGRES_DB: profile2
      POSTGRES_USER: 'profile1'
      POSTGRES_PASSWORD: 'profile2'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis-data:
  mongodb-data:
  postgres_data:

